# include:
# - template: Security/SAST-IaC.latest.gitlab-ci.yml

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/releases/terraform:1.1.6

variables:
  CHANGE_DIRS: default
  TF_CACHE_KEY: default
  TF_ROOT: default
  TF_STATE_NAME: default
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}
  PROD: "false"

before_script:
  - echo "${TF_ROOT}"
  - echo "${TF_STATE_NAME}"
  - echo "${TF_CACHE_KEY}"
  - echo "${TF_ADDRESS}"
  - cd ${TF_ROOT}

stages:
  - init
  - validate
  - build
  - deploy

cache:
  key: ${TF_CACHE_KEY}
  paths:
    - ${TF_ROOT}/.terraform/

init:
  stage: init
  script:
    - gitlab-terraform init

# validate:
#   stage: validate
#   script:
#     - gitlab-terraform validate

build:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

deploy:
  stage: deploy
  script:
    - gitlab-terraform apply
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $PROD == "false"
      when: on_success
