// generated by cdktf get
// ../modules/module1
import { TerraformModule } from 'cdktf';
import { Construct } from 'constructs';
export interface Module1Options {
  /**
   * undefined
   */
  readonly suffix: string;
  /**
   * undefined
   */
  readonly value: string;
}
export class Module1 extends TerraformModule {
  private readonly inputs: { [name: string]: any } = { }
  public constructor(scope: Construct, id: string, options: Module1Options) {
    super(scope, id, {
      source: '../modules/module1',
    });
    this.suffix = options.suffix;
    this.value = options.value;
  }
  public get suffix(): string {
    return this.inputs['suffix'] as string;
  }
  public set suffix(value: string) {
    this.inputs['suffix'] = value;
  }
  public get value(): string {
    return this.inputs['value'] as string;
  }
  public set value(value: string) {
    this.inputs['value'] = value;
  }
  protected synthesizeAttributes() {
    return this.inputs;
  }
}
